spring:
  datasource:
    url:
      'jdbc:postgresql://localhost:5432/shahraz'
    username: postgres
    password: 1111
  jpa:
    show-sql: on
    generate-ddl: on
    hibernate:
      ddl-auto: 'update'
  jackson:
    date-format: 'yyyy-MM-dd'
  kafka:
    bootstrap-servers: 'localhost:9092'



